spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: yyc
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
server:
  port: 8804