server:
  port: 8805
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yyc
  redis:
    password: 123456
    host: 192.168.47.128
    port: 6379
    timeout: 5000ms

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:config/logback-spring.xml